name: Mobile Ci
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/mobile/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'apps/mobile/**'

jobs:
  mobile-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './apps/mobile/package-lock.json'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Type check
        run: npm run tsc -- noEmit

      - name: Run unit tests with coverage
        run: npm run test:coverage

      - name: Run missing-key check
        run: node scripts/check-missing-keys.js
